### ISSUE TITLE
不错的功能，非常好的功能awesome

### ISSUE THREAD

**Issue by xiaohuazi123** [chenxizhang/gpt-translator#7]
https://github.com/marketplace/actions/gpt-translator 如果大家有开源github项目，或者经常要编写多语言文档，你可能会比较抓狂，我最新出炉的这个github action你值得拥有哈

**Comment by chenxizhang** [comment]
@xiaohuazi123  谢谢你的反馈，欢迎你尝试使用，希望有所帮助，也欢迎分享给你的朋友

**Comment by chenxizhang** [comment]
欢迎在这里讨论 （https://github.com/chenxizhang/gpt-translator/discussions ） @xiaohuazi123
